/* Database schema to keep the structure of entire database. */

CREATE TABLE animals ( 
    id INT GENERATED BY DEFAULT AS IDENTITY, 
    name VARCHAR(40) NOT NULL, 
    date_of_birth DATE NOT NULL, 
    escape_attempts INT NOT NULL, 
    neutered BOOLEAN, 
    weight_kg DECIMAL NOT NULL );

